---
abstract: 'Create mock external-command easily'
author:
  - 'Takuya Tsuchida <tsucchi@cpan.org>'
build_requires:
  Capture::Tiny: 0
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Mock-ExternalCommand
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Variable::Expand::AnyLevel: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/tsucchi/p5-Test-Mock-ExternalCommand.git
version: 0.02
